import {
  Fan,
  Zap,
  Lightbulb,
  Droplet,
  Battery,
  ToggleRight,
  Wrench,
  Wind,
  Cable,
  Activity,
  Sun,
  Snowflake,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

export type ProductCard = {
  id: string;
  icon: LucideIcon;
  title: string;
  brand: string;
  brandColor: string;
  brandTextColor?: string;
  bg: string;
  use: string;
  howTo: string;
  steps: string[];
  service: string;
  price: string;
};

export const productCards: ProductCard[] = [
  {
    id: "fan",
    icon: Fan,
    title: "सीलिंग फैन",
    brand: "TOOFAN / HAVELLS",
    brandColor: "oklch(0.65 0.24 35)",
    bg: "linear-gradient(180deg, oklch(0.2 0.06 270), oklch(0.13 0.05 240))",
    use: "घर, ऑफिस, दुकान, स्कूल, हॉल",
    howTo: "रेगुलेटर से स्पीड कंट्रोल। सीजन अनुसार रिवर्स स्विच।",
    steps: [
      "हुक मजबूत करें, डाउन रॉड लगाएं।",
      "वायरिंग: लाल(फेज), काला(न्यूट्रल), हरा(अर्थ)।",
      "ब्लेड संतुलित करें, कैनोपी फिट करें।",
    ],
    service: "हर 6 माह बियरिंग ग्रीस, कैपेसिटर चेक।",
    price: "₹1,299 से",
  },
  {
    id: "mcb",
    icon: Zap,
    title: "MCB ब्रेकर",
    brand: "HAVELLS",
    brandColor: "oklch(0.72 0.18 230)",
    bg: "linear-gradient(180deg, oklch(0.2 0.04 280), oklch(0.13 0.04 270))",
    use: "DB बॉक्स, घरेलू/कमर्शियल सर्किट सुरक्षा",
    howTo: "ऑन/ऑफ स्विच। ओवरलोड या शॉर्ट सर्किट पर ट्रिप।",
    steps: [
      "DB रेल पर क्लिप करें।",
      "इनकमिंग फेज ऊपर, आउटगोइंग नीचे।",
      "न्यूट्रल लिंक से कनेक्ट करें।",
    ],
    service: "हर 3 माह टेस्ट बटन दबाएं (RCCB/RCBO हो तो)।",
    price: "₹149 से",
  },
  {
    id: "bulb",
    icon: Lightbulb,
    title: "LED बल्ब",
    brand: "PHILIPS",
    brandColor: "oklch(0.55 0.2 250)",
    bg: "linear-gradient(180deg, oklch(0.2 0.04 270), oklch(0.15 0.04 280))",
    use: "घर, दुकान, स्ट्रीट लाइट (वाटरप्रूफ)",
    howTo: "होल्डर में लगाएं, स्विच ऑन। डिमेबल न हो तो डिमर न लगाएं।",
    steps: ["B22/E27 होल्डर में स्क्रू करें।", "वोल्टेज 220-240V AC चेक करें।"],
    service: "धूल साफ करें। जलने पर बदलें, मरम्मत नहीं होती।",
    price: "₹79 से",
  },
  {
    id: "pump",
    icon: Droplet,
    title: "मोनोब्लॉक पंप",
    brand: "CROMPTON",
    brandColor: "oklch(0.6 0.24 25)",
    bg: "linear-gradient(180deg, oklch(0.18 0.05 230), oklch(0.13 0.05 220))",
    use: "घरेलू पानी, टंकी भरना, बगीचा",
    howTo: "सक्शन पाइप में पानी भरकर स्टार्ट करें। ड्राई रन न हो।",
    steps: [
      "समतल जगह पर फिक्स करें।",
      "फुट वाल्व लगाएं।",
      "स्टार्टर/कैपेसिटर वायरिंग करें।",
    ],
    service: "हर 6 माह मैकेनिकल सील/बेयरिंग चेक।",
    price: "₹2,499 से",
  },
  {
    id: "inverter",
    icon: Battery,
    title: "इन्वर्टर + बैटरी",
    brand: "LUMINOUS",
    brandColor: "oklch(0.78 0.1 210)",
    bg: "linear-gradient(180deg, oklch(0.2 0.05 280), oklch(0.14 0.05 290))",
    use: "घर, दुकान, पावर बैकअप",
    howTo: "लोड क्षमता अनुसार उपकरण चलाएं। ओवरलोड न करें।",
    steps: [
      "बैटरी हवादार जगह रखें।",
      "टर्मिनल सही पोलैरिटी से जोड़ें।",
      "अर्थिंग अनिवार्य।",
    ],
    service: "हर 3 माह डिस्टिल्ड वाटर टॉपअप, टर्मिनल साफ करें।",
    price: "₹4,999 से",
  },
  {
    id: "switch",
    icon: ToggleRight,
    title: "मॉड्यूलर स्विच/सॉकेट",
    brand: "ANCHOR",
    brandColor: "oklch(0.72 0.18 60)",
    bg: "linear-gradient(180deg, oklch(0.22 0.04 280), oklch(0.15 0.04 270))",
    use: "घर, ऑफिस, होटल वायरिंग",
    howTo: "स्विच दबाकर ऑन/ऑफ। 6A/16A रेटिंग अनुसार लोड।",
    steps: [
      "मेटल बॉक्स में प्लेट फिट करें।",
      "फेज तार स्विच से होकर जाए।",
      "सॉकेट में अर्थ वायर ज़रूरी।",
    ],
    service: "ढीले कनेक्शन चेक, साल में एक बार स्क्रू टाइट।",
    price: "₹45 से",
  },
  {
    id: "pipe",
    icon: Wrench,
    title: "PVC कंड्यूट पाइप",
    brand: "FINOLEX",
    brandColor: "oklch(0.6 0.18 145)",
    bg: "linear-gradient(180deg, oklch(0.18 0.04 220), oklch(0.13 0.04 230))",
    use: "वायरिंग सुरक्षा हेतु दीवार/छत में",
    howTo: "वायर को पाइप के अंदर डालकर जंक्शन बॉक्स तक ले जाएं।",
    steps: [
      "कटिंग और बेंडिंग करें।",
      "सैडल क्लिप से फिक्स करें।",
      "जॉइंट पर सॉल्वेंट लगाएं।",
    ],
    service: "नमी से बचाएं, जॉइंट लीक न हो।",
    price: "₹35/mtr से",
  },
  {
    id: "exhaust",
    icon: Wind,
    title: "एग्जॉस्ट फैन",
    brand: "HAVELLS",
    brandColor: "oklch(0.72 0.18 230)",
    bg: "linear-gradient(180deg, oklch(0.18 0.04 240), oklch(0.13 0.04 250))",
    use: "किचन, बाथरूम, फैक्ट्री",
    howTo: "स्विच ऑन करें, शटर अपने आप खुलेगा।",
    steps: [
      "दीवार में सही साइज का छेद करें।",
      "फ्रेम लगाकर पंखा स्क्रू करें।",
      "वायरिंग कर शटर चेक करें।",
    ],
    service: "ब्लेड और शटर की सफाई, 6 माह में ऑयलिंग।",
    price: "₹699 से",
  },
  {
    id: "wire",
    icon: Cable,
    title: "हाउस वायर",
    brand: "FINOLEX",
    brandColor: "oklch(0.6 0.18 145)",
    bg: "linear-gradient(180deg, oklch(0.2 0.04 280), oklch(0.14 0.04 290))",
    use: "घर/ऑफिस की पूरी वायरिंग",
    howTo: "लोड के अनुसार 1.5/2.5/4 sq.mm चुनें।",
    steps: [
      "पाइप में डालकर फिश करें।",
      "जंक्शन में स्लीव/टेप लगाएं।",
      "अर्थ वायर हरा कलर ही उपयोग करें।",
    ],
    service: "इंसुलेशन टूटे तो तुरंत बदलें।",
    price: "₹999/coil से",
  },
  {
    id: "stabilizer",
    icon: Activity,
    title: "वोल्टेज स्टेबलाइज़र",
    brand: "V-GUARD",
    brandColor: "oklch(0.72 0.2 30)",
    bg: "linear-gradient(180deg, oklch(0.18 0.05 240), oklch(0.14 0.05 250))",
    use: "AC, फ्रिज, TV वोल्टेज सुरक्षा",
    howTo: "स्थिर वोल्टेज देता है। ओवरलोड न करें।",
    steps: [
      "इनपुट सॉकेट से कनेक्ट करें।",
      "आउटपुट में डिवाइस लगाएं।",
      "हवादार जगह रखें।",
    ],
    service: "साल में एक बार रिले/कार्बन ब्रश चेक।",
    price: "₹1,799 से",
  },
  {
    id: "solar",
    icon: Sun,
    title: "सोलर पैनल किट",
    brand: "LUMINOUS",
    brandColor: "oklch(0.78 0.1 210)",
    bg: "linear-gradient(180deg, oklch(0.18 0.05 220), oklch(0.13 0.05 230))",
    use: "घर/दुकान बिजली बिल बचत",
    howTo: "धूप अनुसार चार्ज, इन्वर्टर/बैटरी बैकअप।",
    steps: [
      "छत पर साउथ-फेसिंग लगाएं।",
      "MC4 कनेक्टर से सीरीज/पैरलल।",
      "चार्ज कंट्रोलर/इन्वर्टर सेट करें।",
    ],
    service: "हर माह पैनल साफ करें, कनेक्शन टाइट।",
    price: "₹19,999 से",
  },
  {
    id: "cooler",
    icon: Snowflake,
    title: "एयर कूलर मोटर",
    brand: "CROMPTON",
    brandColor: "oklch(0.6 0.24 25)",
    bg: "linear-gradient(180deg, oklch(0.18 0.05 230), oklch(0.13 0.05 220))",
    use: "डेजर्ट/पर्सनल कूलर",
    howTo: "पानी पंप अलग, फैन मोटर अलग।",
    steps: [
      "पुरानी मोटर खोलें।",
      "नई मोटर शाफ्ट पर ब्लेड फिट करें।",
      "कैपेसिटर सही uF लगाएं।",
    ],
    service: "हर सीजन शुरू में बेयरिंग ऑयलिंग।",
    price: "₹599 से",
  },
];

export const productCategories = [
  {
    title: "🌀 पंखे (Fans)",
    items: [
      "सीलिंग फैन TOOFAN",
      "सीलिंग फैन HAVELLS",
      "टेबल फैन",
      "वॉल फैन",
      "एग्जॉस्ट फैन",
      "पेडेस्टल फैन",
      "BLDC फैन",
      "डेकोरेटिव फैन",
      "इंडस्ट्रियल फैन",
      "मिनी फैन",
    ],
  },
  {
    title: "💡 लाइटिंग (Lighting)",
    items: [
      "LED बल्ब 9W",
      "LED बल्ब 12W",
      "LED बल्ब 15W",
      "ट्यूब लाइट",
      "पैनल लाइट",
      "स्ट्रीट लाइट",
      "फ्लड लाइट",
      "डेकोरेटिव झूमर",
      "स्ट्रिप LED",
      "गरडन लाइट",
      "स्पॉट लाइट",
      "नाइट बल्ब",
    ],
  },
  {
    title: "🔌 स्विच एवं सॉकेट",
    items: [
      "1-Way स्विच",
      "2-Way स्विच",
      "16A सॉकेट",
      "6A सॉकेट",
      "USB सॉकेट",
      "मॉड्यूलर प्लेट",
      "बेल पुश",
      "रेगुलेटर",
      "डिमर",
      "टाइमर स्विच",
      "मोशन सेंसर",
    ],
  },
  {
    title: "⚙️ MCB / DB / सुरक्षा",
    items: [
      "SP MCB",
      "DP MCB",
      "TP MCB",
      "RCCB",
      "RCBO",
      "इसोलेटर",
      "DB बॉक्स 4-वे",
      "DB बॉक्स 8-वे",
      "DB बॉक्स 12-वे",
      "सर्ज प्रोटेक्टर",
    ],
  },
  {
    title: "🔋 पावर बैकअप",
    items: [
      "इन्वर्टर 600VA",
      "इन्वर्टर 1100VA",
      "इन्वर्टर 1500VA",
      "बैटरी 100Ah",
      "बैटरी 150Ah",
      "बैटरी 200Ah",
      "स्टेबलाइज़र AC",
      "स्टेबलाइज़र फ्रिज",
      "UPS",
      "सोलर पैनल",
    ],
  },
  {
    title: "🔧 मोटर / पंप",
    items: [
      "मोनोब्लॉक 0.5HP",
      "मोनोब्लॉक 1HP",
      "सबमर्सिबल पंप",
      "ओपन वेल पंप",
      "बूस्टर पंप",
      "कैपेसिटर 2.5uF",
      "कैपेसिटर 3.5uF",
      "स्टार्टर",
      "प्रेशर स्विच",
      "फुट वाल्व",
    ],
  },
  {
    title: "🧰 केबल / पाइप",
    items: [
      "1.5 sq.mm वायर",
      "2.5 sq.mm वायर",
      "4 sq.mm वायर",
      "6 sq.mm वायर",
      "PVC पाइप 20mm",
      "PVC पाइप 25mm",
      "जंक्शन बॉक्स",
      "बेंड",
      "सैडल क्लिप",
      "टेप इंसुलेशन",
    ],
  },
];

export const totalProducts = 221;
